name: Formatting check
on:
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black

      - uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "CHANGED_SRC_FILES=$(git diff --name-only --diff-filter=ACMRTUXB origin/master | grep -E 'pennylane/')" >> $GITHUB_ENV
          echo "CHANGED_TEST_FILES=$(git diff --name-only --diff-filter=ACMRTUXB origin/master | grep -E 'pennylane/')" >> $GITHUB_ENV

      - name: Run Black
        run: |
          echo "Running black on files: \n $CHANGED_SRC_FILES"
          black -l 100 $CHANGED_SRC_FILES --check
          echo "Running black on files: \n $CHANGED_TEST_FILES"
          black -l 100 $CHANGED_TEST_FILES --check
