name: Formatting check
on:
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Black
        run: |
          git fetch origin master
          echo $(git diff --name-only --diff-filter=ACMRTUXB origin/master -- | grep -E '(pennylane/|tests/)') > changed_files.txt
          if [[ $(cat changed_files.txt) != "" ]]; then
            echo "Running black on files: $(cat changed_files.txt)"
            black -l 100 $(cat changed_files.txt) --check;
            else echo "No changes were found in this PR."
          fi;
