name: Linting
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run linter
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "$(git diff --name-only --diff-filter=ACMRTUXB origin/master | grep -E '(pennylane/|tests/)')"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: True
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--rcfile .pylintrc"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: "-l 100 --check"
          extra-mypy-options: ""
          extra-isort-options: ""
