name: Pylint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pylint

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          git fetch origin master
          echo "CHANGED_SRC_FILES=$(git diff --name-only --diff-filter=ACMRTUXB origin/master -- | grep -E 'pennylane/')" >> $GITHUB_ENV

      - name: Run pylint
        run: |
          echo "------------------------------------"
          echo "Running pylint on files: $CHANGED_SRC_FILES"
          if [[ $CHANGED_SRC_FILES != "" ]]
          then pylint --rcfile .pylintrc $CHANGED_SRC_FILES
          fi
